name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r server/requirements.txt
          pip install pytest

      - name: Run pytest
        run: PYTHONPATH=$PWD pytest -q server/tests

  build:
    name: Build & Push Docker (GHCR)
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: server
          file: server/Dockerfile
          push: true
          tags: |
            ${{ toLower(format('ghcr.io/{0}:latest', github.repository)) }}
            ${{ toLower(format('ghcr.io/{0}:sha-{1}', github.repository, github.sha)) }}

  deploy:
    name: Deploy to Render
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"

