name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          echo "== repo root =="
          ls -la
          echo "== server =="
          ls -la server || true
          echo "== server/tests =="
          ls -la server/tests || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: server
        run: |
          python -V
          pip install -r requirements.txt

      - name: Run pytest
        working-directory: server
        run: |
          pytest -q tests


  build:
    name: Build & Push Docker (GHCR)
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_LATEST: ghcr.io/${{ github.repository }}:latest
      IMAGE_SHA: ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: server
          file: server/Dockerfile
          push: true
          tags: ${{ env.IMAGE_LATEST }},${{ env.IMAGE_SHA }}

  deploy:
    name: Deploy to Render
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"

